server:
  port: 8080

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://spring-boot-app-db.cp24sa2em53x.eu-west-3.rds.amazonaws.com:5432/customer
    username: loocos
    password: springbootapppassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    web-application-type: servlet
  web:
    error:
      include-message: always