name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: loocos
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - 5332:5432

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '17'
          cache: "maven"
      - name: Build and run Unit/Integration test with Maven
        run: mvn -ntp -B verify